hydra:
  run:
    dir: outputs/${experiment_name}/${training_cfg.SetupNN.model_name}/${now:%Y-%m-%d_%H-%M-%S}
defaults:
  - ../configs@_global_.training_cfg: training_v1
  - _self_

# mlflow
path_to_mlflow: mlruns
experiment_name: ???

pretrained: null
# pretrained:
#   run_id : ??? # e.g: 6076d0ebeb414e38b29e5511e7f7d3ab
#   experiment_id: ??? # e.g: 1
#   starting_model: ??? # e.g: DeepTau2018v0_step1_final.tf

# setup
scaling_cfg : ../../scaling_2/scaling_params_v5.json # for DataLoader initialisation
gpu_cfg:
  gpu_mem  : 7 # in Gb
  gpu_index: 0

# logs
log_suffix: step1
