# basic imports
defaults:
  - discriminator: ???
  - plot_setup
  - selection
  - _self_

# mflow run info
path_to_mlflow: ???
experiment_id: ???
run_id: ???

# phase space region
vs_type: ??? # jet/e/mu
dataset_alias: ??? # alias to reference a mixture of input_samples below, e.g. tau_DY_jet_TT
pt_bins: [[20, 40], [40, 100], [100, 1000], [20, 1000]]
eta_bins: [[0, 1.5], [1.5, 3.0], [0, 3.0], [0, 2.3]]
dm_bins: [[0, 1, 2], [10, 11], [0, 1, 2, 10, 11]]

# selection
input_branches: [ 'tau_pt', 'tau_eta', 'tau_decayMode' ] # add here branches with targets/prediction if necessary
cuts: ${apply_dm_cuts}

# inputs/paths
input_samples: # "sample_alias": [list of strings with tau types to be selected]
  ???: ['tau']
  ???: ["${vs_type}"]
path_to_input: null
path_to_pred: '${path_to_mlflow}/${experiment_id}/${run_id}/artifacts/predictions/{sample_alias}/*_pred.h5'
path_to_target: '${path_to_mlflow}/${experiment_id}/${run_id}/artifacts/predictions/{sample_alias}/*_pred.h5'
path_to_weights_taus: null
path_to_weights_vs_type: null
